### ISSUE TITLE
not found QEvent、QUserSession

### ISSUE THREAD

**Issue by zhouzx9999** [yougi/yougi#281]
package org.yougi.event.business.EventBean;

error 

   public List<Event> findUpCommingEvents() {
        JPAQuery query = new JPAQuery(em);
        QEvent qEvent = QEvent.event;*****************

        Calendar today = Calendar.getInstance();
        List<Event> events = query.from(qEvent).where(qEvent.endDate.gt(today.getTime()), qEvent.parent.isNull()).orderBy(qEvent.startDate.asc()).list(qEvent);

        return loadVenues(events);
    }

Error messages:

Multiple markers at this line
	- QEvent cannot be resolved to a type
	- QEvent cannot be resolved to a variable
	- event cannot be resolved or is not a field

**Comment by htmfilho** [comment]
Using Maven, please clean the project and then compile it. It will generate Q* classes using the plugin com.mysema.maven. We face this problem when the IDE doesn't use Maven to build the project.
